import { Venue, Artist, Performance, Banner, SiteInfo, Partner } from '@/types';

export const mockVenues: Venue[] = [
  {
    id: 'nakazaki-hall',
    name: '中崎町レトロビル・アートスペース SPACE ONE',
    nameEn: 'Nakazakicho Heritage Art Space SPACE ONE',
    area: '中崎町・梅田',
    areaEn: 'Nakazakicho / Umeda',
    address: '大阪市北区中崎西2-4-12',
    addressEn: '2-4-12 Nakazaki-nishi, Kita-ku, Osaka',
    access: 'Osaka Metro 谷町線「中崎町駅」徒歩3分 / 各線「梅田駅」徒歩10分',
    accessEn: '3 min walk from Nakazakicho Station (Tanimachi Line) / 10 min from Umeda',
    description: '【HISTORICAL】昭和初期の登録有形文化財・レトロ古民家をリノベーションした濃密な小劇場。歴史的空間と現代舞台表現が交差するプレミアムベニュー。',
    descriptionEn: '[HISTORICAL] An intimate renovated heritage building in retro Nakazakicho, blending historic architectural atmosphere with avant-garde performance.',
    lat: 34.7065,
    lng: 135.5032,
    location: {
      lat: 34.7065,
      lng: 135.5032,
    },
    websiteUrl: 'https://osakafringe.com',
    snsTwitter: 'https://twitter.com/osakafringe',
    snsInstagram: 'https://instagram.com/osakafringe',
    image: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80'
    ],
    capacity: 60,
  },
  {
    id: 'shinsaibashi-under',
    name: '心斎橋 CLUB UNDERGROUND',
    nameEn: 'Shinsaibashi CLUB UNDERGROUND',
    area: 'ミナミ・心斎橋',
    areaEn: 'Minami / Shinsaibashi',
    address: '大阪市中央区西心斎橋1-10-8 B1F',
    addressEn: 'B1F, 1-10-8 Nishi-Shinsaibashi, Chuo-ku, Osaka',
    access: 'Osaka Metro 御堂筋線・長堀鶴見緑地線「心斎橋駅」7番出口すぐ',
    accessEn: 'Directly outside Exit 7 of Shinsaibashi Station',
    description: '【LOCAL】アメリカ村の中心にある地下ライブスペース。街の場所をひらき、アーティストと観客が密に交わる熱気あふれる空間。',
    descriptionEn: '[LOCAL] An energetic underground venue in America-mura, where artists and audience collide in an intimate atmosphere.',
    lat: 34.6722,
    lng: 135.4983,
    location: {
      lat: 34.6722,
      lng: 135.4983,
    },
    websiteUrl: 'https://osakafringe.com',
    snsInstagram: 'https://instagram.com/osakafringe',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80'
    ],
    capacity: 120,
  },
  {
    id: 'nakanoshima-bank',
    name: '中之島 ウォーターフロント・オープンデッキ',
    nameEn: 'Nakanoshima Waterfront Open Deck',
    area: '中之島・北浜',
    areaEn: 'Nakanoshima / Kitahama',
    address: '大阪市北区中之島1-1-28',
    addressEn: '1-1-28 Nakanoshima, Kita-ku, Osaka',
    access: '京阪本線・Osaka Metro 堺筋線「北浜駅」徒歩2分',
    accessEn: '2 min walk from Kitahama Station',
    description: '【CORE】堂島川に面した開放的な公共ショーケース拠点。水都大阪の風を感じながら、大道芸・紙芝居・パブリックアートを展開。',
    descriptionEn: '[CORE] A prime open-air showcase venue along the river, projecting festival energy into the cityscape with street circus and kamishibai.',
    lat: 34.6937,
    lng: 135.5042,
    location: {
      lat: 34.6937,
      lng: 135.5042,
    },
    websiteUrl: 'https://osakafringe.com',
    snsTwitter: 'https://twitter.com/osakafringe',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80'
    ],
    capacity: 200,
  },
  {
    id: 'tennoji-warehouse',
    name: '天王寺 アートファクトリー・ルーフトップ',
    nameEn: 'Tennoji Art Factory Rooftop',
    area: '天王寺・新世界',
    areaEn: 'Tennoji / Shinsekai',
    address: '大阪市天王寺区逢阪2-3-15 屋上',
    addressEn: 'Rooftop, 2-3-15 Osaka, Tennoji-ku, Osaka',
    access: 'JR・Osaka Metro「天王寺駅」北口より徒歩6分',
    accessEn: '6 min walk from Tennoji Station North Exit',
    description: '【LOCAL】通天閣を遠くに望む元倉庫の秘密基地ルーフトップ。夕暮れから夜にかけての古典芸能や作品展示を実施。',
    descriptionEn: '[LOCAL] A converted rooftop space overlooking Tsutenkaku Tower, offering magical dusk atmosphere for traditional arts and site-specific performance.',
    lat: 34.6515,
    lng: 135.5135,
    location: {
      lat: 34.6515,
      lng: 135.5135,
    },
    websiteUrl: 'https://osakafringe.com',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80'
    ],
    capacity: 80,
  },
];

export const mockArtists: Artist[] = [
  {
    id: 'gekidan-osaka-chaos',
    name: '劇団オオサカ・カオス',
    nameEn: 'Gekidan Osaka Chaos',
    origin: '大阪 / 日本',
    originEn: 'Osaka / Japan',
    genre: 'theater',
    profile: '大阪を拠点に活動する身体表現×現代演劇集団。アクロバティックな身体性とエレクトロ浪曲を融合させた独自のスタイルで、国内外の観客から熱狂的な支持を集める。',
    profileEn: 'An Osaka-based avant-garde physical theater company blending energetic acrobatic movement and electro-traditional rokyoku chanting.',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80'
    ],
    websiteUrl: 'https://osakafringe.com',
    snsTwitter: 'https://twitter.com/osakafringe',
    snsInstagram: 'https://instagram.com/osakafringe',
  },
  {
    id: 'alexei-and-maya',
    name: 'Alexei & Maya',
    nameEn: 'Alexei & Maya',
    origin: 'UK / Australia',
    originEn: 'UK / Australia',
    genre: 'street',
    profile: 'エディンバラ・フリンジで数々の賞を受賞した国際デュオ。重力を超える空中アクロバットとファイヤーフープのスペクタクルを展開。',
    profileEn: 'Award-winning international street circus duo bringing breathtaking aerial acrobatics and fire hoop artistry to the city streets.',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80'
    ],
    websiteUrl: 'https://osakafringe.com',
    snsInstagram: 'https://instagram.com/osakafringe',
  },
  {
    id: 'kenji-comedy',
    name: 'Kenji & The International Osaka Club',
    nameEn: 'Kenji & The International Osaka Club',
    origin: '大阪 / 日本',
    originEn: 'Osaka / Japan',
    genre: 'dance',
    profile: '大阪在住のバイリンガルコメディアンたちによるスタンドアップコメディ集団。大阪カルチャー、食文化、国際感覚をユーモラスに交差させたステージを届ける。',
    profileEn: 'A bilingual stand-up comedy collective exploring Osaka culture, food obsessions, and international culture shocks.',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    websiteUrl: 'https://osakafringe.com',
    snsYoutube: 'https://youtube.com/@osakafringe',
  },
  {
    id: 'sakuya-dance',
    name: '咲夜 -Sakuya-',
    nameEn: 'Sakuya',
    origin: '京都・大阪 / 日本',
    originEn: 'Kyoto & Osaka / Japan',
    genre: 'traditional',
    profile: '伝統的な上方舞と現代三味線の奏者によるコラボレーションユニット。幽玄な伝統美にコンテンポラリーの即興性を重ね合わせ、日本の古典芸能を革新する。',
    profileEn: 'A collaboration unit between classical Kamigata dance masters and contemporary shamisen players.',
    image: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=800&q=80',
    websiteUrl: 'https://osakafringe.com',
    snsTwitter: 'https://twitter.com/osakafringe',
  },
  {
    id: 'naniwa-hyoshigi',
    name: 'なにわ拍子木座',
    nameEn: 'Naniwa Hyoshigi-za',
    origin: '大阪 / 日本',
    originEn: 'Osaka / Japan',
    genre: 'kamishibai',
    profile: '昭和レトロな自転車紙芝居を現代に蘇らせる街頭紙芝居師。子どもから大人まで巻き込む参加型パフォーマンスを展開。',
    profileEn: 'Interactive picture storytelling artists performing from vintage bicycle carts. Fun and nostalgic for all generations.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    websiteUrl: 'https://osakafringe.com',
  },
  {
    id: 'studio-ripple',
    name: 'Studio Ripple',
    nameEn: 'Studio Ripple',
    origin: '大阪・ベルリン',
    originEn: 'Osaka & Berlin',
    genre: 'exhibition',
    profile: '大阪とベルリンを拠点に、水・音・光の相互作用を探求するメディアアートコレクティブ。',
    profileEn: 'An international media art collective exploring the intersection of water dynamics, urban acoustics, and responsive light.',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
    websiteUrl: 'https://osakafringe.com',
    snsTwitter: 'https://twitter.com/osakafringe',
    snsInstagram: 'https://instagram.com/osakafringe',
  },
];

export const mockPerformances: Performance[] = [
  {
    id: 'perf-1',
    title: 'ネオ浪速フィジカルシアター『道頓堀の底から』',
    titleEn: 'Neo Naniwa Physical Theater: From the Depths of Dotonbori',
    artists: 'gekidan-osaka-chaos',
    artistId: 'gekidan-osaka-chaos',
    artistName: '劇団オオサカ・カオス',
    artistNameEn: 'Gekidan Osaka Chaos',
    venue: mockVenues[0],
    venueId: 'nakazaki-hall',
    venueName: '中崎町レトロビル・アートスペース SPACE ONE',
    venueNameEn: 'Nakazakicho Heritage Art Space SPACE ONE',
    genre: 'theater',
    genreCustom: 'フィジカルシアター',
    genreCustomEn: 'Physical Theater',
    description: '道頓堀の歴史と都市伝説をアクロバティックな身体表現とエレクトロ浪曲で描き出す、爆発的熱量のノンストップ劇。',
    descriptionEn: 'An explosive non-stop spectacle blending Osaka urban legends, high-energy acrobatics, and electro-traditional rokyoku chanting.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-08T19:00:00+09:00' }, // 会場未指定（メイン会場中崎町ホールを参照）
      { fieldId: 'performancedate', date: '2026-10-10T14:00:00+09:00' }, // 会場未指定（メイン会場中崎町ホールを参照）
      { fieldId: 'performancedate', date: '2026-11-08T18:00:00+09:00', venue: 'shinsaibashi-under' }, // 別会場心斎橋
    ],
    schedules: [
      { date: '2026-10-08', startTime: '19:00', endTime: '20:15', venueId: 'nakazaki-hall', venueName: '中崎町レトロビル・アートスペース SPACE ONE', venueNameEn: 'Nakazakicho Heritage Art Space SPACE ONE', note: 'オープニング記念公演' },
      { date: '2026-10-10', startTime: '14:00', endTime: '15:15', venueId: 'nakazaki-hall', venueName: '中崎町レトロビル・アートスペース SPACE ONE', venueNameEn: 'Nakazakicho Heritage Art Space SPACE ONE' },
      { date: '2026-11-08', startTime: '18:00', endTime: '19:15', venueId: 'shinsaibashi-under', venueName: '心斎橋 CLUB UNDERGROUND', venueNameEn: 'Shinsaibashi CLUB UNDERGROUND', note: 'グランドフィナーレ' },
    ],
    ticketPrice: '前売 ¥2,500 / 当日 ¥3,000 / 学生 ¥1,500',
    ticketPriceEn: 'Adv: ¥2,500 / Door: ¥3,000 / Student: ¥1,500',
    ticketUrl: 'https://osakafringe.com',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=800&q=80'
    ],
    isFeatured: true,
    durationMinutes: 75,
  },
  {
    id: 'perf-2',
    title: 'Fire & Gravity: Street Circus Explosion',
    titleEn: 'Fire & Gravity: Street Circus Explosion',
    artists: 'alexei-and-maya',
    artistId: 'alexei-and-maya',
    artistName: 'Alexei & Maya',
    artistNameEn: 'Alexei & Maya',
    venue: mockVenues[2],
    venueId: 'nakanoshima-bank',
    venueName: '中之島 ウォーターフロント・オープンデッキ',
    venueNameEn: 'Nakanoshima Waterfront Open Deck',
    genre: 'street',
    genreCustom: '大道芸・ファイヤーフープ',
    genreCustomEn: 'Street Circus & Fire Hoop',
    description: 'エディンバラ・フリンジで大絶賛を浴びた国際デュオによる、重力を超える空中技と炎のサーカスパフォーマンス。',
    descriptionEn: 'Award-winning Edinburgh Fringe street sensations bringing breathtaking aerial acrobatics and fire hoop artistry.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-08T17:30:00+09:00' }, // 会場未指定（メイン会場中之島を参照）
      { fieldId: 'performancedate', date: '2026-10-17T16:00:00+09:00' }, // 会場未指定（メイン会場中之島を参照）
      { fieldId: 'performancedate', date: '2026-11-01T15:00:00+09:00', venue: 'tennoji-warehouse' }, // 別会場天王寺
    ],
    schedules: [
      { date: '2026-10-08', startTime: '17:30', endTime: '18:15', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck' },
      { date: '2026-10-17', startTime: '16:00', endTime: '16:45', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck' },
      { date: '2026-11-01', startTime: '15:00', endTime: '15:45', venueId: 'tennoji-warehouse', venueName: '天王寺 アートファクトリー・ルーフトップ', venueNameEn: 'Tennoji Art Factory Rooftop' },
    ],
    ticketPrice: '投げ銭制 (Free / Tip-based)',
    ticketPriceEn: 'Free entry / Tip-based',
    ticketUrl: '',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80'
    ],
    isFeatured: true,
    durationMinutes: 45,
  },
  {
    id: 'perf-3',
    title: '浪速バイリンガルスタンドアップコメディ',
    titleEn: 'Osaka Stories: Bilingual Stand-up Comedy',
    artists: 'kenji-comedy',
    artistId: 'kenji-comedy',
    artistName: 'Kenji & The International Osaka Club',
    artistNameEn: 'Kenji & The International Osaka Club',
    venue: mockVenues[1],
    venueId: 'shinsaibashi-under',
    venueName: '心斎橋 CLUB UNDERGROUND',
    venueNameEn: 'Shinsaibashi CLUB UNDERGROUND',
    genre: 'dance',
    genreCustom: 'スタンドアップ・コメディ',
    genreCustomEn: 'Stand-up Comedy',
    description: '日英バイリンガルで繰り広げられる、大阪の食文化、おかんの掟、カルチャーショックを笑い飛ばす超高速漫才＆スタンドアップ。',
    descriptionEn: 'Hilarious bilingual stand-up comedy exploring Osaka culture, food obsessions, tiger-shirt moms, and international culture shocks.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-11T19:30:00+09:00' },
      { fieldId: 'performancedate', date: '2026-10-24T15:00:00+09:00' },
    ],
    schedules: [
      { date: '2026-10-11', startTime: '19:30', endTime: '20:30', venueId: 'shinsaibashi-under', venueName: '心斎橋 CLUB UNDERGROUND', venueNameEn: 'Shinsaibashi CLUB UNDERGROUND' },
      { date: '2026-10-24', startTime: '15:00', endTime: '16:00', venueId: 'shinsaibashi-under', venueName: '心斎橋 CLUB UNDERGROUND', venueNameEn: 'Shinsaibashi CLUB UNDERGROUND' },
    ],
    ticketPrice: '¥2,000 (1ドリンク付)',
    ticketPriceEn: '¥2,000 (Includes 1 Drink)',
    ticketUrl: 'https://osakafringe.com',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    durationMinutes: 60,
  },
  {
    id: 'perf-4',
    title: '古典×現代 響きあう和の音色と舞',
    titleEn: 'Classical Resonance: Japanese Traditional Dance & Shamisen',
    artists: 'sakuya-dance',
    artistId: 'sakuya-dance',
    artistName: '咲夜 -Sakuya-',
    artistNameEn: 'Sakuya',
    venue: mockVenues[3],
    venueId: 'tennoji-warehouse',
    venueName: '天王寺 アートファクトリー・ルーフトップ',
    venueNameEn: 'Tennoji Art Factory Rooftop',
    genre: 'traditional',
    genreCustom: '古典芸能・現代三味線',
    genreCustomEn: 'Traditional Arts & Modern Shamisen',
    description: '伝統的な三味線と上方舞にコンテンポラリーの即興性を融合。夕暮れのルーフトップで繰り広げられる幽玄のひととき。',
    descriptionEn: 'Fusing traditional shamisen and Kamigata dance with modern improvisation against the evening Osaka skyline.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-18T17:00:00+09:00' },
      { fieldId: 'performancedate', date: '2026-11-03T17:30:00+09:00' },
    ],
    schedules: [
      { date: '2026-10-18', startTime: '17:00', endTime: '18:00', venueId: 'tennoji-warehouse', venueName: '天王寺 アートファクトリー・ルーフトップ', venueNameEn: 'Tennoji Art Factory Rooftop' },
      { date: '2026-11-03', startTime: '17:30', endTime: '18:30', venueId: 'tennoji-warehouse', venueName: '天王寺 アートファクトリー・ルーフトップ', venueNameEn: 'Tennoji Art Factory Rooftop' },
    ],
    ticketPrice: '¥2,000',
    ticketPriceEn: '¥2,000',
    ticketUrl: 'https://osakafringe.com',
    image: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=800&q=80',
    durationMinutes: 60,
  },
  {
    id: 'perf-5',
    title: '街頭紙芝居レボリューション 2026',
    titleEn: 'Street Kamishibai Revolution 2026',
    artists: 'naniwa-hyoshigi',
    artistId: 'naniwa-hyoshigi',
    artistName: 'なにわ拍子木座',
    artistNameEn: 'Naniwa Hyoshigi-za',
    venue: mockVenues[2],
    venueId: 'nakanoshima-bank',
    venueName: '中之島 ウォーターフロント・オープンデッキ',
    venueNameEn: 'Nakanoshima Waterfront Open Deck',
    genre: 'kamishibai',
    genreCustom: '街頭紙芝居・水飴つき',
    genreCustomEn: 'Interactive Street Kamishibai',
    description: '自転車の荷台に乗せた手作り木枠から始まる、昔懐かしくも新しい参加型街頭紙芝居。子どもから大人まで大人気。',
    descriptionEn: 'Interactive picture storytelling performed from a vintage bicycle cart. Fun and nostalgic for all ages.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-10T13:00:00+09:00' },
      { fieldId: 'performancedate', date: '2026-10-25T13:00:00+09:00' },
    ],
    schedules: [
      { date: '2026-10-10', startTime: '13:00', endTime: '13:40', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck' },
      { date: '2026-10-25', startTime: '13:00', endTime: '13:40', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck' },
    ],
    ticketPrice: '無料 (Free)',
    ticketPriceEn: 'Free Admission',
    ticketUrl: '',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    durationMinutes: 40,
  },
  {
    id: 'perf-6',
    title: '都市の呼吸：水都大阪インスタレーション',
    titleEn: 'Urban Breath: Aqua Metropolis Osaka Art Installation',
    artists: 'studio-ripple',
    artistId: 'studio-ripple',
    artistName: 'Studio Ripple',
    artistNameEn: 'Studio Ripple',
    venue: mockVenues[2],
    venueId: 'nakanoshima-bank',
    venueName: '中之島 ウォーターフロント・オープンデッキ',
    venueNameEn: 'Nakanoshima Waterfront Open Deck',
    genre: 'exhibition',
    genreCustom: 'サウンド＆ライト展示',
    genreCustomEn: 'Sound & Light Art Installation',
    description: '川の水位と音響データをリアルタイムで光と立体物に変換する空間作品展示。会期中常時鑑賞可能。',
    descriptionEn: 'An immersive interactive art installation translating river water level and acoustic data into mesmerizing light sculptures.',
    dates: [
      { fieldId: 'performancedate', date: '2026-10-08T11:00:00+09:00' },
      { fieldId: 'performancedate', date: '2026-11-08T11:00:00+09:00' },
    ],
    schedules: [
      { date: '2026-10-08', startTime: '11:00', endTime: '20:00', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck', note: '常設展示' },
      { date: '2026-11-08', startTime: '11:00', endTime: '20:00', venueId: 'nakanoshima-bank', venueName: '中之島 ウォーターフロント・オープンデッキ', venueNameEn: 'Nakanoshima Waterfront Open Deck', note: '常設展示' },
    ],
    ticketPrice: '無料 (Free)',
    ticketPriceEn: 'Free Admission',
    ticketUrl: '',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
    durationMinutes: 60,
  },
];

export const mockBanners: Banner[] = [
  {
    id: 'banner-instagram',
    title: '公式Instagramでフェスティバルの熱気をチェック！',
    titleEn: 'Follow Our Official Instagram for Live Highlights!',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80',
    linkUrl: 'https://www.instagram.com/osakafringe',
    type: 'instagram',
    alt: 'Osaka Fringe Official Instagram',
    description: '最新の公演写真や舞台裏動画を毎日配信中。#OsakaFringe で投稿しよう！',
    descriptionEn: 'Daily show photos, backstage stories and live highlights. Tag #OsakaFringe!',
  },
  {
    id: 'banner-tourism',
    title: '大阪観光局 公式ポータルサイト',
    titleEn: 'Osaka Convention & Tourism Bureau Official Portal',
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=800&q=80',
    linkUrl: 'https://osaka-info.jp/',
    type: 'tourism_osaka',
    alt: 'Osaka Convention & Tourism Bureau',
    description: '大阪のグルメ・観光・宿泊・文化情報を網羅する公式観光ガイド。',
    descriptionEn: 'Your essential guide to Osaka tourism, food culture, accommodations, and city attractions.',
  },
];

export const mockSiteInfo: SiteInfo = {
  siteTitle: '大阪文化万博Osaka Fringe 2026',
  siteTitleEn: 'Osaka Fringe 2026',
  heroTagline: '街の一角を、世界の舞台へ。',
  heroTaglineEn: 'Turning Every Corner of Osaka into a World Stage.',
  heroSubtitle: '大阪の街じゅうが、舞台になる。\n\n劇場、広場、歴史的建築、カフェ、商店街。\n大阪各地の会場とイベントをめぐりながら、さまざまな表現に出会う1か月。',
  heroSubtitleEn: 'The entire city of Osaka becomes a stage.\n\nTheaters, public plazas, historic buildings, cafes and shopping streets become places to encounter performance as you move through the city.',
  festivalPeriod: '2026年10月8日(木) 〜 11月8日(日)',
  festivalPeriodEn: 'OCTOBER 8 – NOVEMBER 8, 2026',
  locationSummary: '大阪市内・大阪近郊各所',
  locationSummaryEn: 'Across Osaka and surrounding areas',
  aboutTitle: '大阪の街じゅうが、舞台になる。',
  aboutTitleEn: 'The City of Osaka Becomes a Stage.',
  aboutText: '大阪文化万博Osaka Fringe 2026は、劇場だけでなく、広場、歴史的建築、商業施設、カフェなど、街のさまざまな場所を舞台にするオープンアクセス型の芸術祭です。\n\nジャンル、国籍、キャリアを問わず参加を受け付け、多様なアーティストと観客が大阪の街で出会います。\n\nいつもの場所が舞台になり、街を巡るなかで、まだ知らなかった表現に出会う。\n\n文化芸術が特別な場所の中だけではなく、大阪の日常へあふれだしていくことを目指しています。',
  aboutTextEn: '大阪文化万博Osaka Fringe 2026 is an open-access arts festival that turns not only theaters but also plazas, historic buildings, commercial spaces, cafes and other places across the city into stages.\n\nWe welcome participation across genres, nationalities and career stages, creating encounters between diverse artists and audiences throughout Osaka.\n\nFamiliar places become stages, and moving through the city becomes a chance to discover expression you did not know before.\n\nOur aim is for arts and culture to spill beyond dedicated venues and into everyday life in Osaka.',
  donationTitle: '次の表現者が、大阪から育つ土壌をつくる。',
  donationTitleEn: 'Creating a City Where the Next Generation of Artists Can Grow.',
  donationText: '大阪には、街の中から新しい表現が生まれてきた歴史があります。\n\n1980年代から1990年代にかけて、大阪では小劇場文化が大きく花開きました。劇場やライブハウスだけでなく、公園やストリートにも表現の場があり、まだ広く知られていない表現者が観客と出会い、次の舞台へ進んでいく流れがありました。\n\n大きな舞台に立つ前に、小さな舞台がある。\n名前を知られる前に、誰かに見つけてもらえる場所がある。\n完成された表現だけでなく、まだ形になりきっていない挑戦にも観客がいる。\n\nそんな環境を、もう一度大阪につくりたい。\n\n大阪文化万博Osaka Fringe 2026は、そのための土壌をつくるプロジェクトです。',
  donationTextEn: 'Osaka has a history of new forms of expression emerging from the city itself.\n\nFrom the 1980s through the 1990s, Osaka\'s independent theater culture flourished. Beyond theaters and live houses, parks and streets also became places for expression, where artists who were not yet widely known could meet audiences and move on to their next opportunity.\n\nBefore a large stage, there is a small one.\nBefore a name becomes known, there is a place to be discovered.\nAnd even an experiment that is not yet fully formed can have an audience.\n\nWe want to create that kind of environment in Osaka again.\n\n大阪文化万博Osaka Fringe 2026 is a project to build that foundation.',
  donationStories: [
    {
      fieldId: 'donationstory',
      sectionKey: 'HISTORY',
      title: 'もう一度、大阪から。',
      titleEn: 'Once Again, From Osaka.',
      text: '私たちが取り戻したいのは、その時代そのものではありません。\n\n「やってみよう」と思った人が挑戦でき、誰かがそれを見つけ、次の機会につながっていく流れです。\n\n時代も、表現の方法も、社会のルールも変わりました。\n\nだからこそ、今の大阪に合った新しい仕組みとして、その流れをつくり直したいと考えています。',
      textEn: 'We are not trying to recreate the past itself.\n\nWhat we want to rebuild is the cycle in which someone can decide to try, someone else can discover that attempt, and it can lead to the next opportunity.\n\nThe times, forms of expression and social rules have changed.\n\nThat is exactly why we want to rebuild this cycle in a way that fits Osaka today.',
    },
    {
      fieldId: 'donationstory',
      sectionKey: 'MESSAGE',
      title: '挑戦できる場所がなければ、\n次の文化は生まれない。',
      titleEn: 'Without Places to Take Risks,\nthe Next Culture Cannot Emerge.',
      text: '才能があっても、発表する場所がなければ届きません。\n\n場所があっても、観客と出会えなければ次につながりません。\n\nそして、新しい表現には、ときに既存の制度やルールとの調整も必要です。\n\nOsaka Fringeでは、劇場だけではなく、広場、歴史的建築、商業施設、店舗など、街のさまざまな場所を表現の場としてひらいていきます。\n\nプロ・アマ、ジャンル、キャリアを問わず、多くのアーティストが挑戦できる機会をつくる。\n観客が、まだ知らない表現者と出会える機会をつくる。\n海外のアーティストも大阪で表現しやすい環境を考える。\n\nそして、安全や地域との共存を大切にしながら、行政や関係機関とも対話を重ね、より挑戦しやすい文化環境を育てていきます。\n\n私たちが目指しているのは、一人のスターをつくることではありません。\n\n次の誰かが育つ可能性を、大阪の街のあちこちにつくることです。',
      textEn: 'Talent cannot reach people without a place to be presented.\n\nA place alone is not enough if artists cannot meet an audience and move on to what comes next.\n\nNew forms of expression also sometimes require careful coordination with existing systems and rules.\n\nOsaka Fringe opens up many kinds of places across the city as spaces for expression: not only theaters, but plazas, historic buildings, commercial spaces and local businesses.\n\nWe want to create opportunities for artists to take risks regardless of genre or career stage; opportunities for audiences to encounter artists they have not yet discovered; and an environment in which international artists can more easily create and perform in Osaka.\n\nAt the same time, we will value safety and coexistence with local communities, and continue dialogue with public authorities and related organizations to build a cultural environment that makes more experimentation possible.\n\nOur goal is not to manufacture a single star.\n\nIt is to create possibilities for the next person to grow, throughout the city of Osaka.',
    },
    {
      fieldId: 'donationstory',
      sectionKey: 'ENVIRONMENT',
      title: '挑戦できる文化環境を、\n長い時間をかけて育てる。',
      titleEn: 'Building a Cultural Environment for Experimentation,\nOver the Long Term.',
      text: '新しい文化活動を広げていくためには、会場、安全管理、道路や公共空間の利用、海外アーティストの受け入れなど、多くの制度やルールとの調整が必要です。\n\nルールを無視するのではなく、ルールの中でできる挑戦を増やす。\n\nその実績を積み重ねながら、行政や関係機関とも対話し、より多様な文化活動が生まれやすい環境をつくっていきます。\n\n一度きりのイベントではなく、次の挑戦が続いていく仕組みを大阪に残すこと。\n\nそれもOsaka Fringeの役割だと考えています。',
      textEn: 'Expanding new cultural activity requires coordination across many systems and rules, including venues, safety management, the use of roads and public spaces, and the reception of international artists.\n\nThe aim is not to ignore rules, but to increase what can be attempted within them.\n\nBy building a record of responsible practice and continuing dialogue with public authorities and related organizations, we want to create an environment in which a wider range of cultural activity can emerge.\n\nOsaka Fringe should not end as a one-off event. We want to leave Osaka with a framework in which the next challenge can continue.',
    },
    {
      fieldId: 'donationstory',
      sectionKey: 'PREFORM',
      title: '小さな支援も、\n次の舞台につながります。',
      titleEn: 'Every Contribution Can Lead\nto the Next Stage.',
      text: '1,000円でも、3,000円でも、10,000円でも。\n\n寄付の大きさにかかわらず、一人ひとりの参加がOsaka Fringeを支える力になります。\n\n観客として公演を見に行くこと。\nアーティストのことを誰かに話すこと。\nSNSで公演を紹介すること。\n\nそして、可能であれば寄付という形で支えること。\n\nOsaka Fringeは、アーティストや運営だけでつくるものではありません。\n\n街にいる一人ひとりが、このフェスティバルの一部です。',
      textEn: 'Whether it is ¥1,000, ¥3,000 or ¥10,000, every contribution matters.\n\nSupporting Osaka Fringe is not only about the size of a donation.\n\nGoing to see a performance.\nTelling someone about an artist.\nSharing a show on social media.\n\nAnd, when possible, supporting the festival through a donation.\n\nOsaka Fringe is not created by artists and organizers alone.\n\nEveryone in the city can be part of this festival.',
    },
    {
      fieldId: 'donationstory',
      sectionKey: 'CLOSING',
      title: '次の誰かが、\n始められる大阪へ。',
      titleEn: 'A City Where the Next Artist Can Begin.',
      text: '一つの公演から、次の表現へ。\n一人の観客から、次の観客へ。\n一つの場所から、街のあちこちへ。\n\nすぐに結果が出ることばかりではありません。\n\nそれでも、挑戦できる場所を増やし、その挑戦を見つける人を増やしていけば、大阪からまた新しい文化が生まれてくるはずです。\n\nspill over ― 文化芸術が街にあふれだす。\n\nその未来を、一緒につくってください。',
      textEn: 'From one performance to the next expression.\nFrom one audience member to another.\nFrom one place to many corners of the city.\n\nThe results will not always appear immediately.\n\nBut if we increase the places where people can take risks, and increase the number of people who discover those attempts, new culture can emerge from Osaka again.\n\nspill over — arts and culture spilling into the city.\n\nHelp us build that future together.',
    },
  ],
  donationImpacts: [
    {
      fieldId: 'donationimpact',
      label: 'CREATE OPPORTUNITIES',
      title: 'アーティストが挑戦できる機会を増やす',
      titleEn: 'Create More Opportunities for Artists to Take the Next Step',
      text: '若手だけではありません。\n\n初めて舞台に立つ人、活動を続けてきた人、新しいジャンルに挑戦する人。\n\nキャリアに関係なく、表現したい人が次の一歩を踏み出せる機会を増やします。\n\n会場との出会い、発表機会、情報発信、必要な環境整備などを通じて、挑戦そのものを支えます。',
      textEn: 'This is not only about young artists.\n\nIt includes people stepping onto a stage for the first time, people who have continued their practice for years, and people attempting a new genre.\n\nRegardless of career stage, we want to create more opportunities for people with something to express to take their next step.\n\nWe support experimentation itself through connections with venues, opportunities to present work, communication and the practical environment needed to perform.',
    },
    {
      fieldId: 'donationimpact',
      label: 'OPEN THE CITY',
      title: '街の中に、もっと表現の場所をひらく',
      titleEn: 'Open More Places Across the City to Expression',
      text: '文化は、劇場の中だけで生まれるものではありません。\n\n広場、歴史ある建物、商業施設、カフェ、店舗など、普段は舞台ではない場所にも表現の機会をつくります。\n\n街を歩いていたら音楽が聞こえてきた。\nいつもの場所でダンスや演劇に出会った。\n\nそんな偶然が、大阪の日常の中に増えていくことを目指します。',
      textEn: 'Culture does not emerge only inside theaters.\n\nWe create opportunities for expression in places that are not usually stages: public plazas, historic buildings, commercial spaces, cafes and local businesses.\n\nYou are walking through the city and hear music.\nYou encounter dance or theater in a familiar place.\n\nWe want more of those unexpected encounters to become part of everyday life in Osaka.',
    },
    {
      fieldId: 'donationimpact',
      label: 'FIND THE NEXT',
      title: 'まだ知られていない表現者と、観客をつなぐ',
      titleEn: 'Connect Audiences with Artists They Have Not Yet Discovered',
      text: 'アーティストが育つためには、舞台だけでなく観客が必要です。\n\n公演情報を探しやすくすること。\n街を巡りながら次の公演に出会えること。\n初めて見るジャンルにも気軽に足を運べること。\n\nOsaka Fringeは、表現する側だけではなく、新しい表現を見つける観客の文化も育てていきます。',
      textEn: 'Artists need more than a stage; they need an audience.\n\nPerformance information should be easy to find.\nMoving through the city should lead to the next show.\nIt should feel easy to try a genre you have never seen before.\n\nOsaka Fringe aims to cultivate not only people who create, but also a culture of audiences who discover new forms of expression.',
    },
    {
      fieldId: 'donationimpact',
      label: 'BUILD THE FUTURE',
      title: '次の挑戦が続く環境をつくる',
      titleEn: 'Build an Environment Where the Next Challenge Can Continue',
      text: '一度公演を開催して終わりではなく、次の挑戦につながる環境を大阪に残していきます。\n\n会場や地域、行政、企業、文化団体など、さまざまな人たちと関係をつくりながら、新しい表現が生まれ続ける土壌を育てます。\n\n大阪から次の文化が生まれる流れを、長い時間をかけてつくっていきます。',
      textEn: 'The goal is not to hold one performance and stop there. We want to leave Osaka with an environment that leads to the next attempt.\n\nBy building relationships among venues, communities, public authorities, businesses and cultural organizations, we aim to cultivate the conditions in which new expression can continue to emerge.\n\nOver time, we want to rebuild a cycle in which the next culture can grow from Osaka.',
    },
  ],
  donationBankNote: '受領証等が必要な場合は、お問い合わせフォームよりご連絡ください。',
  donationBankNoteEn: 'If you require a receipt or other documentation, please contact us through the inquiry form.',
  donationBankInfo: `金融機関名：大阪シティ信用金庫
支店名：阿倍野支店
口座種別：普通預金
口座番号：8173108
口座名義：オオサカブンカフリンジキコウセツリツジュンビシツ
（大阪文化フリンジ機構設立準備室）`,
  donationBankInfoEn: `Bank: Osaka City Shinkin Bank
Branch: Abeno Branch
Account Type: Ordinary / Savings
Account Number: 8173108
Account Name: OSAKA BUNKA FRINGE KIKOU SETSURITSU JUNBISHITSU`,
  officialInstagramUrl: 'https://www.instagram.com/osakafringe',
  officialXUrl: 'https://twitter.com/osakafringe',
  officialWebsiteUrl: 'https://osakafringe.com',
  contactEmail: 'info@osakafringe.com',
};

export const mockPartners: Partner[] = [
  {
    id: 'partner-octb',
    name: '公益財団法人 大阪観光局',
    nameEn: 'Osaka Convention & Tourism Bureau',
    image: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=800&q=80',
    url: 'https://osaka-info.jp',
    description: '水都大阪の魅力を世界へ発信する大阪観光局。大阪フリンジの観光・インバウンド連携パートナー。',
    descriptionEn: 'Official tourism board promoting Osaka worldwide as an international cultural hub.',
    category: '組織（後援・協力）',
  },
  {
    id: 'partner-tomofes',
    name: 'トモフェス (TOMO FESTIVAL)',
    nameEn: 'TOMO FESTIVAL',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    url: 'https://osakafringe.com',
    description: '大阪を舞台に人と街がつながる都市型カルチャーフェスティバル。連携企画を実施。',
    descriptionEn: 'Urban cultural festival connecting people and community in Osaka.',
    category: '連携イベント・フェス',
  },
  {
    id: 'partner-minami',
    name: 'ミナミフェス (MINAMI FESTIVAL)',
    nameEn: 'MINAMI ART FESTIVAL',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    url: 'https://osakafringe.com',
    description: '心斎橋・道頓堀・アメリカ村を舞台にしたミナミエリア連携アートフェス。',
    descriptionEn: 'Minami area collaborative art and performance festival.',
    category: '連携イベント・フェス',
  },
];